
language: java
install: skip

jdk:
  - oraclejdk12
  - openjdk8
  - openjdk12

# Fix permission errors
before_install:
  - chmod +x gradlew

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/